// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ISB.CLWater.Data.Entities;

public partial class LK_SUFFIX
{
    [Key]
    public int SUFFIX_ID { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string SUFFIX_DESC { get; set; } = null!;

    public bool IS_ACTIVE { get; set; }

    public int CREATED_BY { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CREATED_DATE { get; set; }

    public int EDITED_BY { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime EDITED_DATE { get; set; }

    [InverseProperty("SUFFIX")]
    public virtual ICollection<TBL_PERSON> TBL_PERSON { get; set; } = new List<TBL_PERSON>();
}