// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ISB.CLWater.Data.Entities;

[Keyless]
public partial class TBL_ADDRESS_STAGING
{
    public int ADDRESS_ID { get; set; }

    public int PERSON_ID { get; set; }

    [StringLength(35)]
    [Unicode(false)]
    public string CITY { get; set; } = null!;

    [StringLength(20)]
    [Unicode(false)]
    public string ZIPCODE { get; set; } = null!;

    public int? CREATED_BY { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CREATED_DATE { get; set; }

    public int? EDITED_BY { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? EDITED_DATE { get; set; }

    public int? IS_CURRENT { get; set; }

    public int? STATE_ID { get; set; }

    public int? COUNTRY_ID { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string? ADDRESS_2 { get; set; }

    [StringLength(35)]
    [Unicode(false)]
    public string? OTHER_STATE_DESC { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string? ADDRESS_1 { get; set; }
}